version: "3.9"

services:
  userman:
    image: postgres:15.1-alpine
    container_name: UserManDB
    restart: always
    volumes:
      - ./data/schema.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./data/data.sql:/docker-entrypoint-initdb.d/02-data.sql
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PSW}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"