server:
  port: ${PORT:8080}
logging:
  level:
    org.atmosphere: warn

spring:
  mustache:
    check-template-location: false
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PSW}
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PSW}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


vaadin:
  whitelisted-packages: com.vaadin,org.vaadin,dev.hilla,be.archilios.usermanagement
  launch-browser: true